-- 1번

SELECT E.NAME, 
         CASE 
            WHEN HISTORY_ID IS NULL THEN 'No Change' 
            ELSE E.JOB_ID 
            END AS JOB_ID
  FROM EMPLOYEES E
  LEFT
  JOIN JOB_HISTORY J
    ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
 ORDER 
    BY TO_NUMBER(SUBSTR(E.NAME, 10));
    

-- 2번
SELECT E.NAME, 
       NVL(E.SALARY, 0) AS SALARY, 
       D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  LEFT  
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.NAME LIKE '%Employee 1%'
 ORDER 
    BY TO_NUMBER(SUBSTR(DEPARTMENT_NAME, 12));


-- 3번
SELECT T.ACCOUNT_ID, 
       T.AMOUNT, 
       TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE, 
       A.CUSTOMER_ID, 
       C.NAME
  FROM TRANSACTIONS T
  LEFT
  JOIN ACCOUNTS A
    ON T.ACCOUNT_ID = A.ACCOUNT_ID
  JOIN CUSTOMERS C
    ON A.CUSTOMER_ID = C.CUSTOMER_ID
 WHERE TRANSACTION_DATE BETWEEN ADD_MONTHS(SYSDATE, -6) AND SYSDATE;


-- 4번
SELECT E.JOB_ID, 
       COUNT(*) AS COUNT_EMPLOYEES
  FROM DEPARTMENTS D
  LEFT
  JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 WHERE DEPARTMENT_NAME IN ('Department 3', 'Department 4', 'Department 5', 'Department 6')
 GROUP
    BY E.JOB_ID;
 
-- 5번
SELECT ACCOUNT_TYPE, 
       TRUNC(AVG(BALANCE), 2) AS AVG_BALANCE
  FROM ACCOUNTS
 GROUP
    BY ACCOUNT_TYPE
 ORDER
    BY AVG_BALANCE DESC;

-- 6번
SELECT A.ACCOUNT_ID, 
       COUNT(T.ACCOUNT_ID) CNT
  FROM ACCOUNTS A 
  LEFT 
  JOIN TRANSACTIONS T
    ON A.ACCOUNT_ID = T.ACCOUNT_ID
 GROUP 
    BY A.ACCOUNT_ID
 ORDER 
    BY CNT;
    

-- 7번
SELECT *
FROM 
    (
    SELECT C.CUSTOMER_ID, SUM(T.AMOUNT) TOTAL_AMOUNT
    FROM CUSTOMERS C, ACCOUNTS A, TRANSACTIONS T
    WHERE C.CUSTOMER_ID = A.CUSTOMER_ID AND 
          A.ACCOUNT_ID = T.ACCOUNT_ID AND 
          T.TRANSACTION_DATE BETWEEN '20240101' AND '20251231'
    GROUP BY C.CUSTOMER_ID
    ORDER BY TOTAL_AMOUNT DESC
    )
WHERE ROWNUM <= 10;

-- 8번
SELECT E.NAME,
       D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  LEFT 
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.SALARY IS NULL;


-- 9번
SELECT *
  FROM 
      (
        SELECT C.CUSTOMER_ID, MAX(L.AMOUNT) MAX_LOAN
          FROM CUSTOMERS C, LOANS L
         WHERE C.CUSTOMER_ID = L.CUSTOMER_ID
         GROUP 
            BY C.CUSTOMER_ID
         ORDER
            BY MAX_LOAN DESC
      )
 WHERE ROWNUM <= 15;
 
-- 10번
SELECT DEPARTMENT_NAME, 
       COUNT(EMPLOYEE_ID) EMPLOYEES_COUNT
  FROM DEPARTMENTS D, EMPLOYEES E
 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID AND
       E.SALARY BETWEEN 7000 AND 15000
 GROUP
    BY DEPARTMENT_NAME
HAVING COUNT(EMPLOYEE_ID) >= 5
 ORDER
    BY EMPLOYEES_COUNT DESC;