-- 실습과제 7-1
SELECT B.BRANCH_ID, L.NAME, L.AMOUNT
FROM BRANCHES B
LEFT JOIN (SELECT LO.*, C.NAME FROM LOANS LO JOIN CUSTOMERS C ON LO.CUSTOMER_ID = C.CUSTOMER_ID) L
ON B.BRANCH_ID = L.BRANCH_ID
ORDER BY BRANCH_ID;

-- 실습과제 7-2
SELECT NAME, EMAIL
FROM CUSTOMERS C
INNER JOIN ACCOUNTS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE BALANCE >= 50000;

-- 실습과제 7-3
SELECT NAME, AMOUNT
FROM LOANS L, CUSTOMERS C
WHERE STATUS = 'PENDING' AND L.CUSTOMER_ID = C.CUSTOMER_ID;