CREATE TABLE FINANCIAL_INSTITUTION (
    FINANCE_ID NUMBER PRIMARY KEY,
    FINANCE_NAME VARCHAR2(50) NOT NULL
);


CREATE TABLE LOAN_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    FINANCE_ID NUMBER NOT NULL,
    CONSTRAINT FK_FINANCE_ID FOREIGN KEY (FINANCE_ID) REFERENCES FINANCIAL_INSTITUTION(FINANCE_ID),
    PREFERENTIAL CHAR(1),
    AVERAGE_PROFIT FLOAT,
    MAX_LIMIT NUMBER,
    RELEASE_DATE DATE
);


CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCT(PRODUCT_ID),
    TITLE VARCHAR2(50) NOT NULL, 
    CONTENT LONG, 
    CREATED_AT DATE,
    VIEW_COUNT NUMBER,
    COMMENT_COUNT NUMBER
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    GENDER VARCHAR2(50),
    AMOUNT NUMBER,
    GRADE VARCHAR2(50),
    JOIN_DATE DATE
);

ALTER TABLE REVIEW ADD CUSTOMRE_ID NUMBER ;
ALTER TABLE REVIEW RENAME COLUMN CUSTOMRE_ID TO CUSTOMER_ID;
ALTER TABLE REVIEW ADD CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

CREATE TABLE REPLY (

    REPLY_ID NUMBER PRIMARY KEY,
    REVIEW_ID NUMBER,
    CONSTRAINT FK_REVIEW_ID FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID),
    CUSTOMER_ID NUMBER,
    CONSTRAINT FK_CUSTOMER_ID_2 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONTENT VARCHAR2(100),
    CREATED_AT DATE
    );
    

CREATE TABLE ROOM (
    ROOM_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50) ,
    CREATED_AT DATE
    );
    
CREATE TABLE CHATTING_MEMBER (
     CHAT_MEMBER_ID NUMBER PRIMARY KEY,
     ROOM_ID NUMBER NOT NULL,
     CONSTRAINT FK_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID),
     CUSTORMER_NAME NUMBER,
     CREATED_AT DATE
);

CREATE TABLE CHAT (
    CHAT_ID NUMBER PRIMARY KEY,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    CUSTOMER_ID NUMBER,
    ROOM_ID NUMBER,
    CONSTRAINT FK_CHAT_ROOM_ID FOREIGN KEY(ROOM_ID) REFERENCES ROOM (ROOM_ID)
    );


INSERT INTO CUSTOMER VALUES (1, '김병주', 'bangzoo@daou.co.kr', '남성', 3000000, '일반', '2025-01-02');
INSERT INTO ROOM VALUES (1, '김병주', '2025-01-02');
INSERT INTO CHAT VALUES (1, '2025-01-02', '2025-01-02', 1, 1);
INSERT INTO CHATTING_MEMBER VALUES(1, 1, 1, '2025-01-02');
INSERT INTO financial_institution VALUES(1, '키움증권');
INSERT INTO LOAN_PRODUCT VALUES(1, '키움대출', 1, 'Y', 2.5, 30000000, '2025-01-02');
INSERT INTO REVIEW VALUES(1, 1, '키움대출 좋네요', '우대금리 있음',  '2025-01-02', 10, 10, 1);
INSERT INTO REPLY VALUES(1, 1, 1, '좋네요', '2025-01-02');