-- 실습과제 6-1
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT, COUNT(LOAN_ID) AS LOAN_COUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY STATUS;

-- 실습과제 6-2
SELECT TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') AS MONTH, SUM(AMOUNT) AS MONTHLY_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM')
HAVING SUM(AMOUNT) >= 10000;

-- 실습과제 6-3
SELECT BRANCH_ID, AVG(AMOUNT) AS AVG_AMOUNT, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID
