-- 실습과제 5-1
SELECT *
FROM CUSTOMERS
ORDER BY NAME ASC, EMAIL DESC;

-- 실습과제 5-2
SELECT *
FROM ACCOUNTS
ORDER BY BALANCE DESC, ACCOUNT_ID ASC;

-- 실습과제 5-3
SELECT *
FROM TRANSACTIONS
ORDER BY TRANSACTION_TYPE ASC, AMOUNT DESC;

-- 실습과제 5-4
SELECT *
FROM LOANS
ORDER BY STATUS ASC, AMOUNT DESC;
