-- 실습과제 2-1
SELECT NAME, PHONE
FROM CUSTOMERS
WHERE ADDRESS = 'Address 100';

-- 실습과제 2-2
SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
WHERE BALANCE >= 50000;

-- 실습과제 2-3
SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
WHERE AMOUNT < 0;

-- 실습과제 2-4
SELECT AMOUNT, CUSTOMER_ID
FROM LOANS
WHERE STATUS = 'APPROVED';
