-- 실습과제 1-1
SELECT NAME,EMAIL 
FROM CUSTOMERS;

-- 실습과제 1-2
SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS;

-- 실습과제 1-3
SELECT AMOUNT, TRANSACTION_TYPE
FROM TRANSACTIONS;


-- 실습과제 2-1
SELECT NAME, PHONE
FROM CUSTOMERS
WHERE ADDRESS = 'Address 100';

-- 실습과제 2-2
SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
WHERE BALANCE >= 50000;

-- 실습과제 2-3
SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
WHERE AMOUNT < 0;

-- 실습과제 2-4
SELECT AMOUNT, CUSTOMER_ID
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 실습과제 3-1
SELECT NAME, EMAIL
FROM CUSTOMERS
WHERE PHONE LIKE '555-1000%';

-- 실습과제 3-2
SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
WHERE ACCOUNT_TYPE = 'SAVINGS' AND BALANCE >= 10000;

-- 실습과제 3-3
SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTION_TYPE = 'DEPOSIT' AND AMOUNT >= 1000;


-- 실습과제 3-4
SELECT LOAN_ID, AMOUNT
FROM LOANS
WHERE AMOUNT >= 50000 AND STATUS = 'PENDING';